name: atcoder_generate

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/atcoder_generate.yml'
      - 'mkdocs.yml'
      - 'scripts/atcoder/generate.jl'
      - 'src/atcoder/**'
  workflow_run:
    workflows:
      - atcoder_fetch_statement
      - atcoder_fetch_user
    types:
      - completed

concurrency:
  group: atcoder_generate
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to origin/main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Set up Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      
      - name: Generate
        run: julia scripts/atcoder/generate.jl

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-include-markdown-plugin
      
      - name: Link /src
        run: ln -s ../src docs/src

      - name: Build
        run: |
          mkdocs build -d build

      # - name: Deploy
      #   run: ghp-import -n -f -p build
      
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
  
  backup:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Setup Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Install ghp-import
        run: pip install ghp-import

      - name: Push to gh-pages
        run: |
          ghp-import -n -f -b gh-pages github-pages
          git push origin gh-pages