name: atcoder_fetch_user

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/atcoder_fetch_user.yml'
      - 'mkdocs.yml'
      - 'scripts/atcoder/fetch_user.jl'
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Fetch User
        run: julia scripts/atcoder/fetch_user.jl
      
      - name: Commit & Push changes
        run: |
          git add src/atcoder
          git diff --cached --quiet || git commit -m "chore: update fetched user"
          git push