name: ci

on:
    push:
        branches:
            - main
            - master
    schedule:
        - cron: '0 * * * *'

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache Julia packages
              uses: actions/cache@v3
              with:
                path: ~/.julia
                key: ${{ runner.os }}-julia-${{ hashFiles('scripts/fetch_and_generate_docs.jl') }}

            - name: Set up Julia
              uses: julia-actions/setup-julia@v1
              with:
                version: '1.10'

            - name: Generate algorithm docs
              run: julia scripts/fetch_and_generate_docs.jl

            - name: Set up Python & install MkDocs
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Cache pip packages
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') || 'mkdocs' }}

            - name: Install MkDocs and plugins
              run: pip install mkdocs-material mkdocs-awesome-pages-plugin
            
            - name: Build static site
              run: mkdocs build -d build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: build