name: deploy

on:
  workflow_run:
    workflows:
      - atcoder_generate
    types:
      - completed

concurrency:
  group: deploy
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install ghp-import
        run: pip install ghp-import

      - name: Backup to gh-pages
        run: |
          ghp-import -n -f -p -b gh-pages build