name: deploy_atcoder

on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/deploy_atcoder.yml'
      - 'mkdocs.yml'
      - 'scripts/generate/atcoder.jl'
      - 'src/atcoder/**'
  workflow_run:
    workflows:
      - fetch_atcoder
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Generate AtCoder
        run: julia scripts/generate/atcoder.jl

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs and Plugins
        run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-include-markdown-plugin ghp-import

      - name: Build site and Copy src/
        run: |
          mkdir -p build
          mkdocs build -d build
          cp -r src build/src

      - name: Deploy
        run: ghp-import -n -f -p build